### PR TITLE
BuildPDAF: Separate Fortran/C compiler options

### PR DESCRIPTION
**Pull request by jjokella**
- `PDAF_FOPT`
- `PDAF_COPT`

Related to #36  (preparatory for adding separate Fortran/C options in `Stages/2024`)

### CODE REVIEW

**Comment by jjokella** [comment]
This PR is already merged in `stages/2024` and it was needed to give separate compiler options to C / Fortran compilation commands, as is done in eCLM.

https://github.com/HPSCTerrSys/eCLM/blob/c9f334838b4584e8543dc3e6f7e50661433b2055/cmake/SetBuildOptions.cmake#L35-L38

Now a problem mentioned in #36 stays. For the DEBUG compilation:
```
mpif90  -O0 -g -traceback -fpe0 -check all -xHost -r8  -o $TSMP/TSMP2_JURECADC_2024_11_14_stages-2024_eCLM-PDAF_DEBUG/bin/JURECADC_eCLM-PDAF/bin/tsmp-pdaf \
mod_tsmp.o mod_parallel_pdaf.o mod_assimilation.o parser_mpi.o mod_read_obs.o pdaf_terrsysmp.o integrate_pdaf.o init_parallel_pdaf.o finalize_pdaf.o init_pdaf.o init_pdaf_parse.o init_pdaf_info.o assimilate_pdaf.o init_ens.o prepoststep_ens_pdaf.o next_observation_pdaf.o distribute_state_pdaf.o collect_state_pdaf.o init_obs_pdaf.o init_dim_obs_pdaf.o obs_op_pdaf.o prodrinva_pdaf.o init_obsvar_pdaf.o add_obs_error_pdaf.o init_obscovar_pdaf.o  init_n_domains_pdaf.o init_dim_l_pdaf.o g2l_state_pdaf.o l2g_state_pdaf.o prodrinva_l_pdaf.o init_obs_l_pdaf.o init_dim_obs_l_pdaf.o g2l_obs_pdaf.o init_obsvar_l_pdaf.o init_dim_obs_f_pdaf.o init_obs_f_pdaf.o obs_op_f_pdaf.o localize_covar_pdaf.o \
-L$TSMP/TSMP2_JURECADC_2024_11_14_stages-2024_eCLM-PDAF_DEBUG/models/pdaf/lib -lpdaf-d -Wl,--start-group    -qmkl -Wl,--end-group -Wl,-rpath -Wl,/p/software/jurecadc/stages/2024/software/psmpi/5.9.2-1-intel-compilers-2023.2.1/lib -Wl,--enable-new-dtags -Wl,-rpath-link=/p/software/jurecadc/stages/2024/software/pscom/5-default-GCCcore-12.3.0/lib -L/p/software/jurecadc/stages/2024/software/psmpi/5.9.2-1-intel-compilers-2023.2.1/lib -lmpi -ldl -lpthread -lcudart -lstdc++ -lcuda -lrt -lgpfs -lpmix -lmpich -fiopenmp -L/p/software/jurecadc/stages/2024/software/netCDF-Fortran/4.6.1-ipsmpi-2023a/lib -lnetcdff -L/p/software/jurecadc/stages/2024/software/netCDF-Fortran/4.6.1-ipsmpi-2023a/lib -lnetcdff -lnetcdf -L/p/software/jurecadc/stages/2024/software/netCDF/4.9.2-ipsmpi-2023a/lib64 -lnetcdf -lhdf5_hl -lhdf5 -lm -lz -lblosc -lzstd -lbz2 -lsz -lcurl -lpnetcdf -lxml2 $TSMP/TSMP2_JURECADC_2024_11_14_stages-2024_eCLM-PDAF_DEBUG/bin/JURECADC_eCLM-PDAF/lib/libmodel.a -L$TSMP/TSMP2_JURECADC_2024_11_14_stages-2024_eCLM-PDAF_DEBUG/bin/JURECADC_eCLM-PDAF/lib -L$TSMP/TSMP2_JURECADC_2024_11_14_stages-2024_eCLM-PDAF_DEBUG/bin/JURECADC_eCLM-PDAF/lib -leclm -lclm -ldatm -lglc -lgptl -lice -lmosart -locn -lpio -lwav -lesp -lmct2 -lmpeu -lcsm_share
ld: warning: size of symbol `outdir' changed from 1 in $TSMP/TSMP2_JURECADC_2024_11_14_stages-2024_eCLM-PDAF_DEBUG/bin/JURECADC_eCLM-PDAF/lib/libmodel.a(enkf_clm_mod_5.o) to 100 in $TSMP/TSMP2_JURECADC_2024_11_14_stages-2024_eCLM-PDAF_DEBUG/bin/JURECADC_eCLM-PDAF/lib/libmodel.a(wrapper_tsmp.o)
ld: /p/software/jurecadc/stages/2024/software/cURL/8.0.1-GCCcore-12.3.0/lib/libcurl.a(libcurl_la-content_encoding.o): undefined reference to symbol 'ZSTD_isError'
ld: /p/software/jurecadc/stages/2024/software/Blosc/1.21.5-GCCcore-12.3.0/lib/libblosc.so.1: error adding symbols: DSO missing from command line
```

For RELEASE, the linking command is identical except for the compiler flags at the very beginning and there it does not cause problems.

**Comment by jjokella** [comment]
I tried 
- removing `-xHost`: `stages-2024-no-xHost`
- adding additional options `-standard-semantics -no-simd -fpmodel=precise -warn all`
and both together, but the `'ZSTD_isError'` from `libcurl` remained. My feeling is that something is wrong with the linking rather than the compiler options.

Two possibly interesting warnings appeared for our version of `ifx`:
```
ifx: command line warning #10148: option '-no-simd' not supported
ifx: command line warning #10006: ignoring unknown option '-fpmodel=precise'
```
- regarding `no-simd`, we may have to use the openmp-version
-  regarding the `-fpmodel`, I am not sure, this seemingly contradicts the table in https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-ifort-to-ifx.html

**Comment by jjokella** [comment]
When I put the `-Wl,--end-group` to the very end of the `mpif90` linking command, I get a different error. The `ZSTD` Error is replaced by 
```
ld: /p/software/jurecadc/stages/2024/software/cURL/8.0.1-GCCcore-12.3.0/lib/libcurl.a(libcurl_la-openssl.o): undefined reference to symbol 'SSL_get_verify_result@@OPENSSL_1_1_0'
ld: /p/software/jurecadc/stages/2024/software/OpenSSL/1.1/lib/libssl.so.1.1: error adding symbols: DSO missing from command line
```

**Comment by kvrigor** [comment]
Let's try to take a step back: we can discover the minimum linker flags required by a library, say NetCDF: 

```bash
source env/jsc.2024_Intel.sh

# Required flags when compiling with NetCDF C
$ nc-config --libs
-L/p/software/jurecadc/stages/2024/software/netCDF/4.9.2-ipsmpi-2023a/lib64 -lnetcdf

# Required flags when compiling with NetCDF Fortran
$ nf-config --flibs
-L/p/software/jurecadc/stages/2024/software/netCDF-Fortran/4.6.1-ipsmpi-2023a/lib -lnetcdff -L/p/software/jurecadc/stages/2024/software/bzip2/1.0.8-GCCcore-12.3.0/lib64 -L/p/software/jurecadc/stages/2024/software/bzip2/1.0.8-GCCcore-12.3.0/lib -L/p/software/jurecadc/stages/2024/software/netCDF/4.9.2-ipsmpi-2023a/lib64 -L/p/software/jurecadc/stages/2024/software/netCDF/4.9.2-ipsmpi-2023a/lib -L/p/software/jurecadc/stages/2024/software/intel-compilers/2023.2.1/compiler/2023.2.1/linux/compiler/lib/intel64 -lnetcdf -lnetcdf -lm -liomp5 -lpthread

# Required flags when compiling with NetCDF Fortran
$ pnetcdf-config --ldflags
-L/p/software/jurecadc/stages/2024/software/Perl/5.36.1-GCCcore-12.3.0/lib64 -L/p/software/jurecadc/stages/2024/software/Perl/5.36.1-GCCcore-12.3.0/lib -L/p/software/jurecadc/stages/2024/software/intel-compilers/2023.2.1/compiler/2023.2.1/linux/compiler/lib/intel64
```

Here we don't see `-lzstd`,  `-lssl`, `-lcurl`, etc. How did these flags got introduced in the 1st place? A hint in the [linked issue](https://github.com/HPSCTerrSys/TSMP2/issues/36#issuecomment-2475705621):

```
NetCDF_F90_STATIC_LDFLAGS=-L/p/software/jurecadc/stages/2024/software/netCDF-Fortran/4.6.1-ipsmpi-2023a/lib;-lnetcdff;-L/p/software/jurecadc/stages/2024/software/netCDF-Fortran/4.6.1-ipsmpi-2023a/lib;-lnetcdff;-lnetcdf;-L/p/software/jurecadc/stages/2024/software/netCDF/4.9.2-ipsmpi-2023a/lib64;-lnetcdf;-lhdf5_hl;-lhdf5;-lm;-lz;-lblosc;-lzstd;-lbz2;-lsz;-lcurl;-lpnetcdf;-lxml2
```

@jjokella: you can try to investigate how `NetCDF_F90_STATIC_LDFLAGS` got all these flags and examine which ones are truly necessary. You may also check the value of `NetCDF_F90_STATIC_LDFLAGS` when the `BUILD_TYPE=RELEASE`. 

Another helpful exercise is to do a book-keeping of all linker flags. Necessary flags should directly map to a PDAF dependency, e.g. `-leclm -lclm -ldatm -lglc -lgptl -lice -lmosart -locn -lpio -lwav -lesp -lmct2 -lmpeu -lcsm_share` are required by eCLM. Otherwise the extra linker flags might be unnecessary in the first place.

**Comment by jjokella** [comment]
Thanks a lot @kvrigor  for these detailed instructions that I will definitely take up!

Meanwhile, I investigated the issue further myself and found a fix, even though I am not 100% sure why it works:

`-lm` seems to cause problems. When I force it to be a linker flag by changing it to `-Wl,-lm`, the linking process runs through correctly.

Analysis with `-Wl,--trace` gives out that for
- `-lm`  (ERROR)
```
/p/software/jurecadc/stages/2024/software/intel-compilers/2023.2.1/compiler/2023.2.1/linux/compiler/lib/intel64_lin/libimf.a
/lib/../lib64/libm.a
/usr/lib64/libm-2.34.a
/usr/lib64/libmvec.a
/p/software/jurecadc/stages/2024/software/zlib/1.2.13-GCCcore-12.3.0/lib/libz.a
/p/software/jurecadc/stages/2024/software/Blosc/1.21.5-GCCcore-12.3.0/lib/libblosc.a
/p/software/jurecadc/stages/2024/software/zstd/1.5.5-GCCcore-12.3.0/lib/libzstd.a
/p/software/jurecadc/stages/2024/software/bzip2/1.0.8-GCCcore-12.3.0/lib/libbz2.a
/p/software/jurecadc/stages/2024/software/Szip/2.1.1-GCCcore-12.3.0/lib/libsz.a
/p/software/jurecadc/stages/2024/software/cURL/8.0.1-GCCcore-12.3.0/lib/libcurl.a
/p/software/jurecadc/stages/2024/software/PnetCDF/1.12.3-ipsmpi-2023a/lib/libpnetcdf.a
/p/software/jurecadc/stages/2024/software/libxml2/2.11.4-GCCcore-12.3.0/lib/libxml2.a
```
- `-Wl,-lm` (COMPLETES)
```
/lib/../lib64/libm.so
/lib64/libm.so.6
/lib64/libmvec.so.1
/lib64/libmvec.so.1
/p/software/jurecadc/stages/2024/software/zlib/1.2.13-GCCcore-12.3.0/lib/libz.so
/p/software/jurecadc/stages/2024/software/Blosc/1.21.5-GCCcore-12.3.0/lib/libblosc.so
/p/software/jurecadc/stages/2024/software/zstd/1.5.5-GCCcore-12.3.0/lib/libzstd.so
/p/software/jurecadc/stages/2024/software/bzip2/1.0.8-GCCcore-12.3.0/lib/libbz2.so
/p/software/jurecadc/stages/2024/software/Szip/2.1.1-GCCcore-12.3.0/lib/libsz.so
/p/software/jurecadc/stages/2024/software/cURL/8.0.1-GCCcore-12.3.0/lib/libcurl.so
/p/software/jurecadc/stages/2024/software/PnetCDF/1.12.3-ipsmpi-2023a/lib/libpnetcdf.so
/p/software/jurecadc/stages/2024/software/libxml2/2.11.4-GCCcore-12.3.0/lib/libxml2.so
```

**Comment by jjokella** [comment]
Following your advice, I think my `netCDF_F90_STATIC_LDFLAGS` is maybe not even needed and just causing confusing, I think I simply need `-lnetcdff -lpnetcdf`. Maybe use other environment variables - make it more robust. Will investigate more.

**Comment by jjokella** [comment]
My suggestion: I would like to merge this PR simply for its functionality of providing separate compiler options for Fortran files and C files in the PDAF interface.

More discussion around topics from this PR can  be moved to new PRs  (make things clearer IMO)
- NetCDF libraries for PDAF codes (#38)
- Updateing to Stages/2024, in particular to ifx / IntelLLVM

**Pull request merged**
